### ISSUE TITLE
.BOT file not deployed by default 

### ISSUE THREAD

**Issue by martinkearn** [Microsoft/botbuilder-dotnet#1004]
## Version
BotBuilder
c#
v4.0.7 (the GA version released September 2018).

## Describe the bug
The .BOT file included in the Azure Bot Service template is not deployed when the project is published to Azure because the .BOT file has the `Copy to Output Directory` file property set to `Do not copy`.

## To Reproduce
1. Create a new Azure Bot service choosing the V4 C# EchoBot template
2. Download the code
3. Make a change to the .BOT file either directly or via the MSBOT CLI tool (adding a description is fine)
4. Publish the bot project (Visual Studio Publish, GitHub integration etc …. any normal publishing technique)
5. Note that the published version of the project does not have the updated .BOT file. This can be verified by exploring the Azure App Service > Files in Visual Studio Cloud Explorer

## Expected behavior
.BOT is published with the rest of the bot project by default

## Screenshots
Not applicable

## Additional context
Fix is to set the `Copy to Output Directory` .BOT file property to say `Copy Always` in Visual Studio and publish to Azure using normal techniques. Update .BOT file will now be published to the Azure Bot Service.

[bug]

**Comment by corinagum** [comment]
Team is aware of this bug and fix is in the works.

**Comment by sgellock** [comment]
Fix will go out with next Azure portal release.

**Comment by yochay** [comment]
@sgellock and @cleemullins  - this should also be fixed across all samples. Can we have SW do a sweep of all samples?

**Comment by JasonSowers** [comment]
I have confirmed this has been fixed.  Thanks for reporting the issue.

**Comment by reddyavinash5** [comment]
@JasonSowers  I still get this error. I have spent 2 days on this so far very frustrating to keep debugging.

**Comment by CoHealer** [comment]
@reddyavinash5, can you confirm you are on 4.1 or greater? The 4.1 issue manifest says this issue was included however above it says it was removed:

![image](https://user-images.githubusercontent.com/43556801/51063490-1313c180-15b0-11e9-87d3-88de09b39454.png)

@yochay, can you confirm this was addressed?
