### ISSUE TITLE
ChoicePrompt : Choice values are not getting displayed on skype channel(both for skype windows app and skype online)

### ISSUE THREAD

**Issue by utkarsh24** [Microsoft/botbuilder-dotnet#1162]
Hi All, 

I have used choice prompt to show user choices and select one from it,

below is the code sample ....
```
var strs = new List<string>{"Choice 1","Choice 2"};
var choices = ChoiceFactory.ToChoices();
                    await dc.PromptAsync("promptid", new PromptOptions()
                    {
                        Prompt = MessageFactory.Text("Prompt text"),
                        Choices = choices,
                        RetryPrompt = MessageFactory.SuggestedActions(
                            strs,
                            "Reprompt text") as Activity
                    });


 var choicePrompt = new ChoicePrompt(PromptType.ChoicePrompt.ToString(), this.ValidatorRegex, Culture.English);
choicePrompt.Style = ListStyle.Auto; // Also tried SuggestedAction 
this.AddDialog(choicePrompt);
```

While running this code on skype app on windows 10 the choice values are appear for couple of seconds and then disappear, before you can select it.

On Skype Online it does not show choices at all.

apps and Versions 

Windows 10 Enterprice version 1803

Skype desktop app : 
                   Skype version 8.34.0.81
                   Application version 14.34.81.0

 bot framework :  4.1.5 

Could you please help me out how to use choice prompt with skype..?

**Comment by dmvtech** [comment]
The Skype channel does not support SuggestedActions.

There are some options you can use to workaround that. Please find one approach [here](https://stackoverflow.com/questions/45095567/using-custom-api-bot-cant-post-action-card-in-microsoft-teams-channel-using-bot). 

If that approach doesn't work for you, please post a question on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework), with the same information and we can see if we can come up with an alternative.

As this is a limitation of the Skype channel, I am closing this issue.

**Comment by ladeak** [comment]
So the previous choice prompt (v3) supported buttons on Cortana, and afaik on Skype channels too.
If suggested actions is not supported in some channels, I would expect choice prompt (v4) to be smart enough to fall back to the logic used in choice prompt (v3) in these channels.

**Comment by utkarsh24** [comment]
@dmvtech as you said suggestedActions are not supported by the skype channel, which is fine, but i am using it in reprompt text.
Are you saying that ChoicePrompt is not supported by the skype channel??

**Comment by utkarsh24** [comment]
Any updates , or work around...

**Comment by v-kydela** [comment]
@utkarsh24 - You could try using cards. I've described this workaround [here](https://github.com/Microsoft/botbuilder-dotnet/issues/1098#issuecomment-438850587).

I'm wondering why in your code you're using an empty list of choices. Did you mean to put `ChoiceFactory.ToChoices(strs)`?

**Comment by dmvtech** [comment]
After further investigation, this looks like it could be a bug in Skype. I will update if we can confirm that. I would suggest looking at the workaround @v-kydela suggested to see if that will work for you.

**Comment by v-kydela** [comment]
@utkarsh24 - Do you still need help?

**Comment by utkarsh24** [comment]
@v-kydela yes please, it would be helpful.
when this bug is going to be fixed?

**Comment by liamkernighan** [comment]
@dmvtech The preview version of Skype 8.35.76.30 really has this bug fixed. Thank you.

**Comment by liamkernighan** [comment]
@dmvtech Seems like that issue appeared again. I don't see any dialog prompts in 8.35 and 8.36 preview versions. Version 8.34 however works correctly. Where can I write the bug report about it?

**Comment by dmvtech** [comment]
@liamkernighan The preview is not yet final. It is possible that there are intermediate changes that are breaking it but will be fixed in release. I'll keep this open until 8.35 is released and we can confirm resolved.

**Comment by dmvtech** [comment]
@liamkernighan Looks like i've got 8.35 now and the buttons don't show at all. Can you let me know what you have for both the skype version and the application version? For example, I have:

Skype version 8.35.0.76
Application version 14.35.76.0

@TiboC I guess now? I'm trying to get some better answers for you. Anyhow, doesn't seem to be working anyway (by my quick test).

**Comment by liamkernighan** [comment]
@dmvtech Don't know how to guess which application version I have.

For Windows: The problem exists in 8.34.0.78 and 8.35.86.30 Preview. (When 8.35 upgrades automatically to 8.36... preview don't remember the exact 8.36 version, the problem still stands). Version 8.32.0.53 does not have any problems with dialog prompts.

On Android: Skype 8.33.0.43 Does not have any problems. Skype Lite 1.76.76.1 does.

When I talk about problem that means that the buttons don't show at all.

**Comment by bwethington** [comment]
Hi All, PM from Skype here. I believe we have addressed this issue on all 8.35+ builds. You should be able to run "/refresh all" (without quotes) in any chat within Skype to get the latest configuration that should address this.
Thanks for the feedback and patience!

**Comment by bwethington** [comment]
@liamkernighan what you are describing was the issue that should have been resolved in >8.35 builds. The separate issue of not appearing at all should be resolved with the refresh. Can you confirm you're on 8.35?

**Comment by liamkernighan** [comment]
@bwethington For Windows insider preview is not available for me any more. The version 8.35.0.71 for Android, however, works correctly.

**Comment by dmvtech** [comment]
@liamkernighan Sorry; can you clarify? Do you mean that version Skype v8.35 preview is not available on Windows Insider Preview? If so, is the release v8.35? Or are you still only able to be on 8.34 on Windows Insider.

@uthkarshs and @TiboC are you both able to confirm the issue is resolved with 8.35?

**Comment by liamkernighan** [comment]
@dmvtech Skype version 8.36.0.52 (Windows 10 version) has no problems with prompts. When will I be able to get that version for Mac?

**Comment by liamkernighan** [comment]
@dmvtech Skype version 8.36.0.52 (Windows 10 version) has no problems with prompts.
I don't have access to Insider Preview versions for now, so I can't tell you.

When will I be able to get that version for Mac?

**Comment by dmvtech** [comment]
@bwethington Any idea on the time frame for Mac? Also; regarding web.skype.com

**Comment by dmvtech** [comment]
@liamkernighan Sounds like Mac might not be until after the first of the year.

Closing issue as it is Skype issue resolved in version 8.35

**Comment by utkarsh24** [comment]
@dmvtech still there is issue on https://web.skype.com/en/ and https://preview.web.skype.com/
Suggested actions and choices are still not working on web skype

**Comment by Delapouite** [comment]
@utkarsh24 I can confirm that I'm still on 8.34.0.78 on Ubuntu and experiencing the problem.

**Comment by mindmodel** [comment]
You can download Skype beta 8.37.76.92 from https://www.skype.com/en/insider/

Fixed the problem on Win7.

**Comment by CoHealer** [comment]
@utkarsh24, are you still seeing this in the web clients? @Delapouite, please update your client to 8.35 or greater.

**Comment by Delapouite** [comment]
I installed skype through snap, but the package is still not up to date https://snapcraft.io/skype
So:
sudo snap remove skype
sudo snap install skype --channel=insider/stable --classic

**Comment by utkarsh24** [comment]
Hi @CoHealer,
Thanks for the update.
I have updated my skype to latest 8.35 and now it looks fine , i mean confirm buttons and choice list both are available, same is working for  https://preview.web.skype.com/

But web skype (https://web.skype.com/en/) still does not show choices or confirm buttons

**Comment by CoHealer** [comment]
You're welcome. It seems like the fix is undergoing validation in Skype preview. @bwethington, when should preview bits be pushed to production?

**Comment by bwethington** [comment]
The fix should be out everywhere at this point. I think the challenge we have is that we are not hearing any other reports where quick replies are not working on web. Attached is a screenshot of a bot I just tested with. @utkarsh24 is there a specific bot you have seen this with?
![image](https://user-images.githubusercontent.com/2235117/51205443-c9322080-18ba-11e9-8047-8fa978dbb055.png)
