### ISSUE TITLE
Typing indicator not going away in MS Teams channel

### ISSUE THREAD

**Issue by PauwelsYoran** [microsoft/botbuilder-dotnet#1877]
## Version
v4.4.3

## Describe the bug
I was using a typing indicator in my chatbot wich worked fine. However, since a few days the typing indicator in MS Teams just keeps showing for 5 seconds, even when a message has been send; normally this wasn't the case. The typing indicator still works in skype for bussines and webchat.

I used following code to start the indicator.
```
private async Task TypingIndicatorAsync(WaterfallStepContext context) 
       {
            var typing = context.Context.Activity.CreateReply();
            typing.Type = ActivityTypes.Typing;
            typing.ReplyToId = context.Context.Activity.Recipient.Id;
            CancellationToken a = new CancellationToken();
            await context.Context.SendActivityAsync(typing, a);
        }
```

## Expected behavior
I want the indicator to go away when a message has been send by the bot.

[bug]

**Comment by dmvtech** [comment]
@PauwelsYoran Can you confirm; the indicator stays for 5 seconds, regardless of behavior on the user end (for example user just clicks one key)? Will it stay for 5 seconds after the message has been sent? or 5 seconds from the start of the typing activity?

I will see if I can reproduce this.

**Comment by PauwelsYoran** [comment]
I just tested it and it actualy stays for 15 seconds, starting from the moment the indicator function was called. It doesn't matter what the user does. If i call the indicator for second time, while the first indicator is running, it probally cancels the first one and starts the second one. So the total time for the 2 indicators is not 30 seconds but, for example, 20 seconds if I start the second indicator after 5 seconds.

**Comment by dmvtech** [comment]
@PauwelsYoran So, the time limit is determined per channel. But I'm not sure why Teams is not canceling it when receiving another (text) message. I believe it's an issue with Teams. I'll let you know what I can find. 

https://stackoverflow.com/questions/55019929/microsoft-teams-app-typing-indicator-duration

**Comment by cleemullins** [comment]
Looks like a client issue. @dmvtech to push to the Teams repo.

**Comment by dmvtech** [comment]
This is being investigated on the Teams side. I will update when I have more info.

**Comment by PauwelsYoran** [comment]
Any updates on the problem?

**Comment by dmvtech** [comment]
Not yet unfortuntely.

**Comment by csannierfr** [comment]
Hi,

I have the same buf and unfortunaly, it's a big problem ...

What's new ?

**Comment by dmvtech** [comment]
This issue is fixed and being rolled out. It is not yet in all public rings. I will post back when it is.

**Comment by PauwelsYoran** [comment]
Thank you for the help!

**Comment by CoHealer** [comment]
Fix merged, closing

**Comment by VKAlwaysWin** [comment]
@CoHealer @dmvtech hello guys, could you please let me know what and where fix located (github?) and what library I should update to get it ? I am still seeing this issue so I want to make sure I am up to date.

Thank you in advance.

**Comment by rickhellenthal** [comment]
I'm also still experiencing this issue in Teams, other channels work fine. The typing indicator disappears after a while, but it does not when an Activity is sent by the bot.

I first noticed this a while ago when using the desktop and web client, however recently this bug appeared on the mobile app as well. This issue also appeared when I created a new project based on the EchoBot example and added the typing indicator. I'm sending a TypingActivity using the following code:
```C#
await turnContext.SendActivityAsync(Activity.CreateTypingActivity());
```
Again, this works fine in other channels, but not in Teams.

Furthermore, I'd also like more information about the fix as @VKAlwaysWin said.

Thanks.

**Comment by dmvtech** [comment]
I am checking to see if I can get a confirmation on the build that this is fixed in.

**Comment by rafaelbbtsaccount** [comment]
Having the same bug in botbuilder-js.

**Comment by VKAlwaysWin** [comment]
Hi, @dmvtech any updates on this ?

**Comment by dmvtech** [comment]
@VKAlwaysWin Not much. The fix is done, but not still yet in public release rings.

**Comment by dmvtech** [comment]
This should be now fixed worldwide. @PauwelsYoran @csannierfr @VKAlwaysWin @rafaelbbtsaccount @rickhellenthal

**Comment by VKAlwaysWin** [comment]
I can confirm that it is fixed. Thanks. Sorry for late response
