### ISSUE TITLE
Telegram Channel not accepting Landscape and rectangle images when sent as media

### ISSUE THREAD

**Issue by muminasaad** [microsoft/botbuilder-dotnet#2652]
## Version
4.4.4

## Describe the bug
Bot framework connect to various channels including telegram.
Sending image from telegram as media will not work if the image is landscape or rectangle.
The channel logs the following error:
    Sequence contains no matching element

## To Reproduce
1. Create bot
2. Connect to Telegram
3. Open Telegram Bot
4. Send image that is landscape

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by dmvtech** [comment]
Hi @muminasaad

I am not able to reproduce this issue. I tried from both Telegram on Windows (desktop app) and Telegram on Android (phone).

A few questions/points:

- The most recent version of the bot framework is 4.5. Are you able to upgrade and test again?
- What OS/platform are you testing on?
- Have you tried with multiple different landscape images?
- Have you tried debugging locally using [ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/)?
- What language is your bot running in (.NET/Node,Typescript etc)?
- What version of Telegram?

If you want to share your images, I'd be happy to test. Or I can send you the images that I tested with.

**Comment by muminasaad** [comment]
Dear @dmvtech 

i am using bot framework version 4.4.4, i cant upgrade as this is a big project for a client and we are too close to release date.

OS is windows

yes multiple landscape images and rectangular images.

yes i have connected to ngrok to my local bot but the call itself was not reaching the bot.

BotFramework .Net Version C#

Telegram Latest Version

Send images as media not files you are correct. 

![photo_2019-10-03_14-57-02](https://user-images.githubusercontent.com/5983341/66161225-7b21a080-e634-11e9-8d37-8232289e00a8.jpg)

Image is attached

you can share the files with me

the bug is that the file doesnt reach the bot if it was as media but as files it reaches the bot.

**Comment by dmvtech** [comment]
Ok, I found some odd behavior, but not sure if it is the same as yours. I'm doing more testing.

Here's what I used to test:
https://github.com/dmvtech/randomstuff/blob/master/dog.jpg
https://github.com/dmvtech/randomstuff/blob/master/seattle2.jpg

**Comment by dmvtech** [comment]
Ok. My apologies. 😆

I don't know what strangeness I was witnessing last week, but I can definitely reproduce this now.

**Comment by dmvtech** [comment]
Tested entirely with .jpg files.

Tested square image: failure to receive event.
Tested same image, one pixel thinner (portrait): failure
Tested same image, one pixel wider (landscape): failure

**Comment by muminasaad** [comment]
@dmvtech hhhhhhhhhhhhhhhh as usual we the developer need to return a bug unable to reproduce at least one to believe it is a bug :P

**Comment by arturl** [comment]
Fix available -- should be deployed before 10/18

**Comment by dmvtech** [comment]
@arturl This is still reproducing for me. Can you give us an update on the fix?

**Comment by arturl** [comment]
I'll update this ticket when the fix is deployed.

**Comment by arturl** [comment]
The fix has been deployed, enjoy!
