### ISSUE TITLE
Severe slowness after little use with replace dialog

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#4986]
I am using replace dialog interchangeably in a scenario (it also results with another reported issue of null reference issue microsoft/BotFramework-Composer#4816).
After little use the bot slows that significantly. I suspect it is in the SDK foundation but since manifested in Composer filed here first.

# Repro
1. Setup Topdialog, child dialog A, child dialog B
2. On prompt child dialog A replaces itself with child dialog B
3. on promopt child dialog B replaces itself with child dialog A
4. keep interacting with the bot between each round (q/a)

Repease a few times, hit mentioned issue, go to top dialog and repeat scenario. ==> bot slows down.

**Comment by scheyal** [comment]
## Video of repro ([link](https://microsoft-my.sharepoint-df.com/:v:/p/eyals/EQ_0wpiuipBEiSHpbG7g5h4BSEBoI6sXAQ56wJUNA6cgzQ?e=KSP8IV))
* Start showing the slowness after a bit of use (I suspect it has nothing to do with replace dialog)
* run a few turns of utterance/response, switch between LUIS/orchestrator to show that it has nothing to do with LU
* Restart conversation
* Show that it starts fast and slows down
(be patient with the video, I jotted notes on the side, didn't realize it only captured the active window).

**Comment by garypretty** [comment]
Adding comments here that I shared with @scheyal offline that might help.  Given the scenario that @scheyal shared with me, it is conceivable that, after a few minutes, you could end up with a significant number of nested dialogs which might explain the slowness?  Just a theory.

You probably want to update the scenario and retest using the following points.

From my initial glance over the pattern, I would need to validate but I think what you need is.

•	You top dialog should have a call to RestartDialog once you call whichever child dialog the user chooses, so that when the child dialog returns, it shows the menu again.
•	If you are in a child dialog (LUIS or Orchestrator in your case) and you want to show the menu again, you just call EndDialog.  This will pop the dialog off the stack and return back to root, which will loop to show the menu.
•	Only call ReplaceDialog if you want to replace with a sibling – if you call ReplaceDialog for the TopDialog, you essentially end up with TopDialog being a child of itself.

**Comment by scheyal** [comment]
@garypretty  - this is irrelevant to the scenario as far as I can tell. Also, I tried all these variations with BeginDialog (there's no RestartDialog) and it didn't work.

**Comment by garypretty** [comment]
@scheyal was this addressed by the new recursive error / warning?

**Comment by scheyal** [comment]
No. Issue is still bad. Also, the recursive bug is still a bug.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
