### ISSUE TITLE
Several unit tests fails in UTC+xx (East UTC) time zones

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/botbuilder-dotnet#745]
When executing tests in a time zone east to UTC (e.g. UTC+01) several unit tests fail due to DatetimeOffset conversion.

AggregatedExceptions show the following error message: `The UTC time represented when the offset is applied must be between year 0 and 10,000`.

![image](https://user-images.githubusercontent.com/805847/42588956-a93e960a-853f-11e8-84cd-dff517e59258.png)

Failing unit tests belong to several test projects and it is related to the `TestFlow` class.

![image](https://user-images.githubusercontent.com/805847/42588976-bc5ebc42-853f-11e8-9641-de40b71d539c.png)

Unit tests does not fail in UTC or West UTC (e.g. UTC-01)

![image](https://user-images.githubusercontent.com/805847/42588992-cb1e0634-853f-11e8-854c-dcf79e4322b4.png)

**Comment by cleemullins** [comment]
This was fixed by PR #747

**Comment by JuanAr** [comment]
We are reopening this issue since we are still seeing 7 tests failing with the same error: `System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset`

![image](https://user-images.githubusercontent.com/805847/42831965-19fab824-89f0-11e8-8cb9-0f33df66dc15.png)

Note: The `BotAdapted_Bracketing` unit tests is fixed in PR #4868.
